### ISSUE TITLE
Does this work? And can it be that these units are set to single touch?

### ISSUE THREAD

**Issue by ropg** [strange-v/FT6X36#1]
Hi @strange-v,

Thank you for writing this. I'm trying to see if this can be used for the M5Stack Core2 hardware, which has an FT6336. I have a question:

* It would appear that the FT6336 in the M5Stack unit is configured for single touch. Or maybe I simply do not understand what an equipment maker can customise. It seems to me that there is a way to tell it what the maximum X and Y values fro the touch panel are, and then it scales to that. (Or not?) Is this also how one sets the dimensions?

**Comment by strange-v** [comment]
Hi @ropg,

It was long ago when I started writing this library (and then abandon it), so I don't remember all details. AFAIR there is no way to switch the device into a single touch mode, but, most probably, the used library supports only 1 point.

After a touch event chip generates interrupt, and then you can read specific addresses to get available information about the event. The most important information: coordinates, event type (start, end, move). The chip itself doesn't scale anything, it is up to a library on how to process the coordinates.

Do you have FT6X36 datasheet with i2c protocol details? I can share if needed.

**Comment by ropg** [comment]
I have the Datasheet with the Application Note. The driver for the device indeed only reads one point. It's just that when I press two points on the screen, it reads a position somewhere in the middle. But only if I press them on same horiz line, it shows only one of them when on a vertical line. Maybe it's the way the touchpad is wired?

**Comment by ropg** [comment]
I am thinking of using your code as a basis for an attempt at writing my own driver. I've never really written interrupt service routines, but your example should help. It would really help me to know why and in what state you abandoned it before I start tinkering though...

**Comment by strange-v** [comment]
I don't know where I read it, but two-point touch detections work only on different parts of the display (probably in landscape orientation).

This library was created for a specific project, but then that project was postponed, so I didn't finish the library. The idea was to detect touch start, move, and touch end (for single-point only) and I was able to get all the required information from the chip.

**Comment by strange-v** [comment]
I have just checked and it seems that basic functionality is already implemented in the library (single tap and drag events).
I'll put all things together, add an example, and commit the update (probably today).

**Comment by ropg** [comment]
I wrote my own library, which does everything from basic touch detection to touch event generation, etc etc. The tocuh screen on the device in question is only multi-touch in the vertical dimension, which is a bit weird, but OK...

**Comment by strange-v** [comment]
Nice to hear this. So I suppose this issue can be closed.
