### ISSUE TITLE
Trying your library with same GoodDisplay 2.7 touch

### ISSUE THREAD

**Issue by martinberlin** [strange-v/FT6X36#2]
Thanks for the lib it looks nice and compiles good.
Can you be so kind to share how you connected this display? Got one and the touch interface but even reading the [PDF specs](http://www.e-paper-display.com/DESPI-C03_SCHaf89.pdf?method=picker&flag=all&id=0a6210c0-76c0-45d3-86dd-b379ae71e12f&fileId=865&v=0.zip) 
I don’t seem to wire it properly since I cannot get any readings from ESP32 
![8BBC2B80-49F7-4639-956B-D512172C8E82](https://user-images.githubusercontent.com/2692928/94328947-1f73c400-ffb7-11ea-8964-971785d02b74.jpeg)

Connected GND option to TP (Touch panel)
ESP32 - Good display PCB
GND  -> GND (Is connected to BUSY also when is TP)
3.3v   -> CS
21  -> SDA I2C
22  -> SDL I2C
25   -> INT
Did you had to use pull-ups of 10K on the i2C data/clock lines?

Thanks and sorry for the wiring question that has little to do with the library itself...

**Comment by strange-v** [comment]
I do not have a fancy HAT, I use an older ESP32 kit (with a socket for a screen only). To connect the touch I just soldered a bare socket to an old PCB.
![Image](https://i.imgur.com/0ok31bd.jpg)
The connection is simple (Screen - ESP32):
GND - GND
INT - GPIO15
RST - Not connected
VDD - 3.3V
SCL - GPIO22
SDA - GPIO21

Seems that your HAT is for Raspberry Pi. I2C bus is missing on the left header, probably it populated on the bottom connector.
What is your current wiring?
As you can see I do not use pull-ups (but it's safer to use them).

**Comment by martinberlin** [comment]
Great thanks for the picture @strange-v  
I think I will go the same way since this HAT is useless as it is, you can only select either I2C or SPI communication so it's a big thing just for the touch. Your take looks much better.

Actually I edited the first message and added the wiring it looks similar just with INT in another pin. But like it is now is not reading the I2C header I just get: 
Starting...
REG 0xA8: 0xFF

I measured both I2C lines and are already pulled up to 3.3 volts if I see that right. I might try to add 10K resistances but I think I have another problem, thanks for the heads up!

**Comment by strange-v** [comment]
Yes, probably it'll be easier to connect touch directly using something like this https://www.aliexpress.com/item/4000493248794.html
I just don't know how lines are routed in that HAT.

**Comment by martinberlin** [comment]
Some advancements being made:
Starting...
REG 0xA8: 0x11
REG 0xA3: 0x64
registerTouchHandler()

Now I2C is working. What I still cannot see happening is the touch itself, measuring INT pin with the multimeter seems to be at 1.8v fixed, does not move at all when touching the epaper. 
The reason was the the touch comes with a flat wire extensor and one of the sides was connected in the opposite way, so of course was all dead, but luckily not inversely connected, just no connection at all. Still researching after the INT status

**Comment by strange-v** [comment]
Seem I've forgotten to add a pin initialization into the library, should be
`pinMode(_intPin, INPUT_PULLUP);`

You can add it to your code (and I'll test and add it to the library later).

PS.
I didn't test this library heavily. Recently decided to finalize it at least somehow because a few people tried to use it in the fully incomplete state.

**Comment by martinberlin** [comment]
Works great. 
One small correction, I was getting : 
error: prototype for 'uint8_t FT6X36::debugInfo()' does not match any in class 'FT6X36'

When activating FT6X36_DEBUG
It's just because the header file this function is declared as void instead of:

```c
#ifdef FT6X36_DEBUG
	uint8_t debugInfo();
#endif
```

**Comment by strange-v** [comment]
Thank you, I'll commit a fix soon.

**Comment by martinberlin** [comment]
Just if this can help someone using good display touch HAT:
![IMG-20200926-WA0012](https://user-images.githubusercontent.com/2692928/94340521-ca5d9f80-0002-11eb-81eb-a493b0551761.jpeg)
The connector goes facing up in the PCB (blue plastic down)
But on the yellow cable extensor that you can see on the photo right after the Touch microchip, both ends, go with this connector facing down (so blue on the top)
However I don't recommend this hat since is build in a way that you can either use the epaper SPI or the I2C touch. But not both at the same time (unless you hack the PCB in am ugly way)
Thanks a lot for your help and the library!

**Comment by martinberlin** [comment]
Hey strange-v, 
Started a new repo where I will try to make UX on the esp32 with this;
https://github.com/martinberlin/epaper-ux-esp32
Just if you want to put it in your radar 😉

**Comment by strange-v** [comment]
Nice.
My initial intention was to use the e-ink screen (and this lib) as a part of a control panel for the apartment heating system, but then priorities shifted. I have a plan to come back to this, so I'll follow your repo.

**Comment by martinberlin** [comment]
Great thanks.
I also have an Open source ESP-IDF component that is called [CalEPD](https://github.com/martinberlin/cale-idf) that lets you have full control of the Epaper classes and is a bit faster than GxEPD.
Starting with Espressif IDF has a bit more higher learning curve than Arduino framework but it pays off and I really like how it builds up together. My dream would be to integrate also this library inside the component at some point so when you instantiate a display it comes already with touch and GFX together. Because now the issue is that if you do a display.setRotation(1) you are rotating only the GFX library but not the touch since are two separate systems.

If we integrate it together in our own component then this could be handled and is transparent for the user implementing this.
Maybe if you like we can talk about this in the future. I‘m also busy with other client work and is hard to find the time to do the things that I desire. Nice to met you!
My name is Martin and I live in Berlin.

**Comment by strange-v** [comment]
Very interesting project (CalLED).

I know about Espressif IDF, but Arduino has a big community and therefore a lot of ready to use libs. The good thing that using the Arduino framework on ESP32 you can easily access RTOS functionality.
Talking about frameworks and RTOS, I also tried Mbed OS, it's really promising embedded OS for ARM microcontrollers (unfortunately, popular chinese versions do not have WiFi support). But the learning curve there is steeper too.

setRotation and some other functionality were planned, but yes, probably it is quite useful to have a single driver (let's call it so) for the display and the touch screen.

Yes, lack of time is a common problem nowadays. Not sure that I'll be able to contribute to your idea/project but let's see.
Nice to meet you too! And feel free to contact me via the public email in case you would like to discuss something IOT related but not tightly related to this particular lib.
Volodymyr, from Ukraine.

**Comment by martinberlin** [comment]
My fork for ESP-IDF of your library is starting to take shape:
https://github.com/martinberlin/FT6X36-IDF/commit/23ed518b8f3744d964d76c03923ebdd4a53291ae
